sonar.projectKey=ShevinuM_spidey-wars-episode-1
sonar.organization=shevinum
sonar.sources=src,scripts
sonar.tests=src,scripts,test
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/unit/lcov.info
sonar.coverage.exclusions=src/scenes/**,src/ui/**,src/config/**,src/main.ts,src/test-hooks.ts,scripts/*.ts,test/**
sonar.cpd.exclusions=src/ui/backdrops/**,src/config/cutscenes/**,**/*.test.ts
